# Generated by Django 4.0.4 on 2022-05-15 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ListaFamiliares', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='familiares',
            new_name='familiaLopez',
        ),
    ]
