# Generated by Django 4.0.4 on 2022-05-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ListaFamiliares', '0002_rename_familiares_familialopez'),
    ]

    operations = [
        migrations.AddField(
            model_name='familialopez',
            name='años',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
